pipeline {
  agent any

  stages {
    stage('docker login & pull') {
       steps{
         withCredentials([usernamePassword(credentialsId: 'dockerhub_creds', passwordVariable: 'PWD', usernameVariable: 'USR')]){
         sh """
          docker login -u $USR -p $PWD
       """
       } 
        sh "docker pull clmkathy/my_ttt:1.0"
        sh "docker images"
    
       }     
    }

    stage('run container&deploy') {
      steps {
        sh 'docker ps -q -a --filter "name=me_tic_tac_toe" | xargs -r docker rm -f'
        sh "docker run -d -p 8090:3000 --name me_tic_tac_toe clmkathy/my_ttt:1.0"
        sh "docker ps -a"
        sh "docker rmi clmkathy/my_ttt:1.0"
        sh "docker images"
      }
    }
  }

  post {
    // stage ('delete'){
      // echo 'delete image'
      // sh "docker rm -f clmkathy/my_ttt:1.0"
    // }
    failure {
         echo "这个阶段 完蛋了.... $currentBuild.result"
      }
    success {
            echo "这个阶段 成了.... $currentBuild.result"
      }
    }
}  
