pipeline {
  agent any

  stages {
    stage ('Build Image') {
      steps {
        sh """
          docker build -t clmkathy/my_ttt:v1 .
          docker images
        """
      }
    }
    stage('docker login & push') {
       steps{
         withCredentials([usernamePassword(credentialsId: 'dockerhub_creds', passwordVariable: 'PWD', usernameVariable: 'USR')]){
         sh """
          docker login -u $USR -p $PWD
          docker push clmkathy/my_ttt:v1
       """
       } 

       }     
    }

    stage('run container&deploy') {
      steps {
        sh 'docker ps -q -a --filter "name=me_tic_tac_toe" | xargs -r docker rm -f'
        sh "docker run -d -p 8090:3000 --name me_tic_tac_toe clmkathy/my_ttt:v1"
        sh "docker ps -a"
        
        sh "docker images"
      }
    }
  }

  post {
    always{
      //  echo "delete image"
      // sh "docker rmi clmkathy/my_ttt:v1"
      echo "clean the workspace whatever"
      cleanWs()
    }
    failure {
         echo "这个阶段 完蛋了.... $currentBuild.result"
      }
    success {
            echo "这个阶段 成了.... $currentBuild.result"
      }
    }
}  
